COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//lib:onos-yang-model',
]

yang_osgi_jar(
  deps = COMPILE_DEPS,
  name = 'onos-apps-yangdemo-yangmodel',
  srcs = glob(['src/main/**/*.yang']),
  visibility = [
    'PUBLIC'
  ],
)
